### ISSUE TITLE
IAM permission to run

### ISSUE THREAD

**Issue by rucciva** [huaweicloud/cloudeye-exporter#54]
hi, what is the permission required for an IAM user to be used by this project. currently i give IAM read only access and CES read only access but i still got the following error

```
recover error: failed to get domain id, No domain id found, please select one of the following solutions:1. Manually specify domain_id when initializing the credentials.2. Use the domain account to grant the current account permissions of the IAM service.3. Use AK/SK of the domain account.
```

IAM read only access
```
{
    "Version": "1.1",
    "Statement": [
        {
            "Action": [
                "iam:*:get*",
                "iam:*:list*",
                "iam:*:check*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

CES read only access
```
{
    "Version": "1.1",
    "Statement": [
        {
            "Action": [
                "ces:*:get*",
                "ces:*:list*",
                "*:*:get*",
                "*:*:list*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**Comment by cxl123156** [comment]
CES，RMS，EPS and ELB read access is required

**Comment by rucciva** [comment]
Hi @cxl123156 , thanks for the reply.
i did grant the following permisison as you pointed out but i still got the following error 

<img width="340" alt="Screenshot 2023-09-07 at 08 31 48" src="https://github.com/huaweicloud/cloudeye-exporter/assets/4647473/e8fb1236-927d-4282-945d-c5edf5a1471e">


```
  [SYS.RDS-1694049463985-1694050063985] recover error: failed to get domain id, No domain id found, please select one of the following solutions:1. Manually specify domain_id when initializing the credentials.2. Use the domain account to grant the current account permissions of the IAM service.3. Use AK/SK of the domain account.
 ```
 
 my clouds.yml setting is following:
 
 ```
global:
  prefix: "huaweicloud"
  port: ":8087"
  metric_path: "/metrics"
  scrape_batch_size: 300

auth:
  auth_url: "https://iam.ap-southeast-4.myhuaweicloud.com/v3"
  access_key: "<redacted>"
  secret_key: "<redacted>"
  user_name: ""
  password: ""
  domain_name: "<redacted>"
  region: "ap-southeast-4"
  project_id: "<redacted>"
  project_name: "ap-southeast-4"

```
